name: Jekyll site CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.38.0
      with:
        ruby-version: 2.5
        bundler-cache: true
    - name: Ruby deps
      run: gem install json kramdown jekyll bundler
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Python deps
      run: pip install pyyaml
    - name: Check all lessons
      run: make lesson-check-all | tee check-messages.txt
    - uses: actions/upload-artifact@v2
      with:
        name: check-messages
        path: check-messages.txt
    - name: Build site
      run: make --always-make site

