name: Test recipes

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if files/recipe_example.yml has not changed
          CACHE_NUMBER: 1
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('files/recipe_example.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"
          miniconda-version: "latest"
          channels: conda-forge
      - name: Install mamba
        shell: bash -l {0}
        run: conda install mamba
      - name: Install esmvaltool from conda
        shell: bash -l {0}
        run: mamba install esmvaltool
      - name: Get config-user file
        shell: bash -l {0}
        run: esmvaltool config get_config_user
      - name: Cache datasets
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if data/dataset.urls has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/climate_data
          key: ${{ runner.os }}-datasets-${{ env.CACHE_NUMBER }}-${{ hashFiles('data/dataset.urls') }}
      - name: Download dataset files for episodes 4 and 5
        shell: bash -l {0}
        run: |
          head -4 data/dataset.urls | grep -v '#' | wget --input-file - --no-clobber --no-verbose --directory-prefix $HOME/climate_data/
      - name: Run all recipes in files/
        shell: bash -l {0}
        run: |
          mkdir ~/esmvaltool_tutorial
          cp files/warming_stripes.py ~/esmvaltool_tutorial/
          for file in files/recipe_warming_stripes*.yml; do $CONDA/envs/test/bin/esmvaltool run $PWD/$file; done
