name: Test recipes

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if files/recipe_example.yml has not changed
          CACHE_NUMBER: 1
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('files/recipe_example.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"
          miniconda-version: "latest"
          channels: conda-forge
      - name: Install mamba
        shell: bash -l {0}
        run: conda install mamba
      - name: Install esmvaltool from conda
        shell: bash -l {0}
        run: mamba install -n test -c conda-forge esmvaltool
      - name: Setup config
        shell: bash -l {0}
        run: |
          esmvaltool config get_config_user
          patch ~/.esmvaltool/config-user.yml << EOF
          44c44
          < #rootpath:
          ---
          > rootpath:
          48c48
          < #  default: ~/default_inputpath
          ---
          >   default: ~/default_inputpath
          EOF
      - name: Cache datasets
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if data/dataset.urls has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/default_inputpath
          key: ${{ runner.os }}-datasets-${{ env.CACHE_NUMBER }}-${{ hashFiles('data/dataset.urls') }}
      - name: Download dataset files for episodes 4 and 5
        run: |
          head -4 data/dataset.urls | grep -v '#' | wget --input-file - --no-clobber --directory-prefix $HOME/default_inputpath/
      - name: Run all recipes in files/
        run: |
          mkdir ~/esmvaltool_tutorial
          cp files/warming_stripes.py ~/esmvaltool_tutorial/
          for file in files/recipe*.yml; do $CONDA/envs/test/bin/esmvaltool run $PWD/$file; done
